export const MOVIES_TYPES = {
    LOAD_MOVIES: "LOAD_MOVIES",
    UPDATE_MOVIES_COUNT: "UPDATE_MOVIES_COUNT",
    UPDATE_SELECTED_GENRES: "UPDATE_SELECTED_GENRES",
    UPDATE_SELECTED_SORTING: "UPDATE_SELECTED_SORTING",
}

export const APP_TYPES = {
    TOGGLE_MODAL: "TOGGLE_MODAL",
    SET_VIEW_MODE: "SET_VIEW_MODE",
    SET_DETAILED_VIEW_DATA: "SET_DETAILED_VIEW_DATA",
}
